apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-sa
  labels:
    app: nginx
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pod-mount-as-env-variable
  labels:
    app: nginx-pod-mount-as-env-variable
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-pod-mount-as-env-variable
  template:
    metadata:
      labels:
        app: nginx-pod-mount-as-env-variable
    spec:
      serviceAccountName: nginx-sa
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "nginx-secretproviderclass-2"
      containers:
        - name: nginx-pod-mount-as-env-variable
          image: nginx
          ports:
            - containerPort: 80
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-k8s-secret-mirror
                  key: password
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-k8s-secret-mirror
                  key: username
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true