apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: nginx-secretproviderclass-2
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "csiDriverEKS"
        objectType: "secretsmanager"
        jmesPath:
          - path: "password"
            objectAlias: "password"
          - path: "username"
            objectAlias: "username"
    usePodIdentity: "true"
  secretObjects:
    - secretName: my-k8s-secret-mirror
      type: Opaque
      data:
        - key: password
          objectName: "password"
        - key: username
          objectName: "username"
